descriptionFormat: '{product.title} - {title}'
handle: accessoires
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Accessoires
productFieldLayouts:
  a61c6870-f516-44f2-bba6-05911b994b87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: de655ae6-487c-4ff7-90f6-594f5a9a3007
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 0fefa22c-485f-4796-88f8-6248c8872169
            userCondition: null
            warning: null
        name: Content
        uid: f94bb65d-340e-44bb-abbf-0460d9f97e27
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'accessoires/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'accessoires/{slug}'
skuFormat: ''
variantFieldLayouts:
  f1d5d64f-ebe4-404e-8727-a36f2f88f33f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 650c944e-b704-49a9-88d7-a0c18e150817
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17468e2f-e32b-45f3-8804-06ea98ea8e58
        userCondition: null
variantTitleFormat: '{product.title}'
