descriptionFormat: '{product.title}'
handle: accessoires
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Accessoires
productFieldLayouts:
  a61c6870-f516-44f2-bba6-05911b994b87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: de655ae6-487c-4ff7-90f6-594f5a9a3007
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: Afbeelding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be22cb79-003d-4a7e-bab2-c408d736e421
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d # Link 1
            instructions: null
            label: Collectie
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60f29c5d-5efd-4a45-af94-de651acac3c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: 'Beschrijving product'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8121e38-5a85-4234-bcbb-d72829174130
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f94bb65d-340e-44bb-abbf-0460d9f97e27
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab1e9ae1-eba0-4b77-9d5c-752874dc9fbd # Filter: shop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 918ab672-d18e-47cc-bf2d-f0bc62faa2d0
            userCondition: null
            warning: null
            width: 100
        name: Filters
        uid: feedc03e-afab-49ad-989d-f0ff22032b2e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 0fefa22c-485f-4796-88f8-6248c8872169
            userCondition: null
            warning: null
        name: Variants
        uid: f347f935-145e-4e1a-80af-887326d685e9
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'accessoires/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'accessoires/{slug}'
skuFormat: ''
variantFieldLayouts:
  f1d5d64f-ebe4-404e-8727-a36f2f88f33f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 650c944e-b704-49a9-88d7-a0c18e150817
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17468e2f-e32b-45f3-8804-06ea98ea8e58
        userCondition: null
variantTitleFormat: '{product.title}'
