descriptionFormat: '{product.title}'
handle: books
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Books
productFieldLayouts:
  0f843c26-1767-4932-80a5-aa3e4ac5413a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 9d2f90b1-5a57-4963-9ef9-b63d9ecff6fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: Afbeelding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03aad3a3-3458-40ae-ae34-6cb341381656
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e6d64dd2-c9e9-410c-81b6-82ffa3358eeb # Link 2
            instructions: null
            label: Collectie
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1b146cc-4d04-48db-b882-ff4b039ef005
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: 'Beschrijving product'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1743a1a-c59c-4dab-a68a-8e80981378d0
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c9b0cb5c-6432-4e5d-a6c0-1f58de8e3785
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 3a140314-d40c-4f35-9068-20d48251014a
            userCondition: null
            warning: null
        name: Variants
        uid: 2eb236e5-1f79-47ce-9163-58abf445c219
        userCondition: null
productTitleFormat: ''
siteSettings:
  0c227af7-cc71-4e70-a370-a1a6b63ddf75: # Français
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'books/{slug}'
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'books/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'books/{slug}'
skuFormat: ''
variantFieldLayouts:
  61ee21c6-6702-4b15-9da2-1349dc8df2fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 9c8ff127-5072-4051-b03e-78625e26cdbd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a2f79e4-83dc-4af4-8d09-fc747d840496 # Unique Combination of Variant Attributes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2f139ca-5fc5-497c-afee-45fde90516bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e190dd2-8dcf-471a-b3e8-ea2900d6d6cb
        userCondition: null
variantTitleFormat: '{product.title}'
