descriptionFormat: '{product.title} - {title}'
handle: cards
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Cards
productFieldLayouts:
  055e50ca-8054-4f49-9ece-fdf0d0641ef8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: bde5c3d8-f28c-4838-805d-3b430864c857
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 8b15bf57-b097-444d-98a4-c396703bf92a
            userCondition: null
            warning: null
        name: Content
        uid: bde9f038-5093-4e0d-8cbf-b82ee6549b46
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab1e9ae1-eba0-4b77-9d5c-752874dc9fbd # Filter: shop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bfd2876-6d8d-4015-920a-9f0cc7a4a311
            userCondition: null
            warning: null
            width: 100
        name: Filters
        uid: 6a532970-a24f-440d-a191-cf3348d0e2b4
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'cards/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'cards/{slug}'
skuFormat: ''
variantFieldLayouts:
  a3799906-6650-438e-8232-6fbd646e0018:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 384968f5-85a6-488b-b890-3082b16393f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85f5a4ad-2577-4ccb-883a-9d0c9430b434
        userCondition: null
variantTitleFormat: '{product.title}'
