descriptionFormat: '{product.title} - {title}'
handle: collaborations
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Collaborations
productFieldLayouts:
  b93dcb8f-e1c9-4868-bb72-8537b25b01b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 43907eaf-8e87-4ce8-bc21-fb0bd3dd4c36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 7a33c93f-708c-4096-b250-01bc274a2b01
            userCondition: null
            warning: null
        name: Content
        uid: 0503f2ae-466b-401e-ae33-1b95541a1d9e
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'collaborations/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'collaborations/{slug}'
skuFormat: ''
variantFieldLayouts:
  f9ca3b4a-f9b1-4227-9a15-b99afac2d85e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: ffa6e234-9f58-4c9e-bab7-558770703c73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cd86519-6651-4dc0-b95a-4b39fed25c44
        userCondition: null
variantTitleFormat: '{product.title}'
