descriptionFormat: '{product.title}'
handle: prints
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Prints
productFieldLayouts:
  6b4b035f-c275-4c04-8e87-2504c03b2c1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 911ac7f9-861e-449d-8b37-298820a30396
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: Afbeelding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1c9a857-0224-4a76-8309-ee58d61f080e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d # Link 1
            instructions: null
            label: Collectie
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab50d416-9ff4-4b0b-aea8-21dd765d45da
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: 'Beschrijving product'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 346c40f7-a926-4d9c-8961-124e4c3b1762
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 52882e48-291e-42ed-b57c-a6f7120d4bf6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab1e9ae1-eba0-4b77-9d5c-752874dc9fbd # Filter: shop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 298d5cb6-a4fc-4be8-9360-31087c0bbe73
            userCondition: null
            warning: null
            width: 100
        name: Filters
        uid: 63a283f0-7e73-4c71-8e19-a434b8d9b58b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 2a6578d6-f90d-44bf-8194-bcfc578c3764
            userCondition: null
            warning: null
        name: Variants
        uid: 58c38e7d-05fc-4b1b-b754-35de43c62637
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'prints/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    hasUrls: true
    template: _commerce/shop/product.twig
    uriFormat: 'prints/{slug}'
skuFormat: ''
variantFieldLayouts:
  47fe391e-a6bd-4e2f-bab2-f11e52f0ba65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 2663bf17-ee95-4d8e-961b-c031742f7765
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a2f79e4-83dc-4af4-8d09-fc747d840496 # Unique Combination of Variant Attributes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36aff79c-cd5d-46cd-96ee-d390fc33f402
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f70d67c8-c5de-468d-b4b3-c239e5a10391
        userCondition: null
variantTitleFormat: '{product.title}'
