descriptionFormat: '{product.title} - {title}'
handle: prints
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: Prints
productFieldLayouts:
  6b4b035f-c275-4c04-8e87-2504c03b2c1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 911ac7f9-861e-449d-8b37-298820a30396
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 2a6578d6-f90d-44bf-8194-bcfc578c3764
            userCondition: null
            warning: null
        name: Content
        uid: 52882e48-291e-42ed-b57c-a6f7120d4bf6
        userCondition: null
productTitleFormat: ''
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # English
    hasUrls: true
    template: ''
    uriFormat: 'prints/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # Nederlands
    hasUrls: true
    template: ''
    uriFormat: 'prints/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
