fieldLayouts:
  fa2f8688-6d65-4f10-9f0e-c376dff50a68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a325790-ed1c-412f-8e50-679266127667
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60677aed-7d79-4d52-ae45-b2b7e22d5f6d
        userCondition: null
handle: about
hasTitleField: true
name: About
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
