fieldLayouts:
  f0e352ef-6b9d-4c19-a8dc-c21691f16576:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d40e6b4-5db5-4369-aa3d-3ccc61ac7a91
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ea70667-2e04-4b0b-8104-efc2a6d6eccf
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
