fieldLayouts:
  2ef3a8b0-35ad-4693-97e0-1eddef760b66:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e42ff672-c235-4bf1-b105-4033769f1adb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 072366a1-39d9-4c91-8e57-6eab946ae6fe # Voornaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba161eae-eba3-4298-9222-34bcdba4ae1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c785f0e6-e64a-4275-979b-4b8f8b74ca7a # Achternaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32d8c9b8-f4c9-4d3a-8246-a1de26792c2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f24636c-4f10-4522-894b-45739e075b70 # Email adres
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e37856f0-f483-4e5a-8249-03ed1cb511cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48abcf61-f6f1-411b-903a-81f034608b53 # Bericht
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eae13cb5-a25a-48ae-9182-dbc3fb64236a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: de221c2a-170f-4e3c-a6de-e3bd484087f0
        userCondition: null
handle: contactMessage
hasTitleField: false
name: Contactbericht
section: 7bfd2eb5-6578-4433-9c41-d19176243b02 # Contact berichten
sortOrder: 1
titleFormat: '{ firstName } { lastName } - { email}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
