fieldLayouts:
  e31ec490-7d85-48eb-8035-26052baac2c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c88c8b81-079d-44d1-9d93-50389018e48a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: thumbnail
            type: craft\fieldlayoutelements\Heading
            uid: aa5d2b92-cbe2-453e-ba7b-6420461a6a34
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9757016b-74fa-4bc1-a608-750c73587d3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: slider
            type: craft\fieldlayoutelements\Heading
            uid: 2f2df4db-be0d-470d-ab0f-35160cd06a5c
            userCondition: null
          -
            elementCondition: null
            fieldUid: d1f9737c-c74a-4ffd-8fde-fed08a33c48c # Afbeelding 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cfdf4d9-9a62-4060-a585-1cbb5a538315
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 899c793d-0ff3-4611-8076-a9ae2dacf8c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c871bcad-3990-4bf3-954f-b29d2e335773 # Filter: gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a7a9da9-8acd-4f10-9189-3b64c2e34f01
            userCondition: null
            warning: null
            width: 100
        name: Filters
        uid: bc26c552-6423-45b4-b9ca-fd4cd71703fe
        userCondition: null
handle: detail
hasTitleField: true
name: Detail
section: 5e45130b-d008-42a5-9107-35670a0d35c3 # Gallery pagina's
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
