fieldLayouts:
  e31ec490-7d85-48eb-8035-26052baac2c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c88c8b81-079d-44d1-9d93-50389018e48a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dfcf780-002f-48dc-b0f0-0dcc79b60f8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: thumbnail
            type: craft\fieldlayoutelements\Heading
            uid: aa5d2b92-cbe2-453e-ba7b-6420461a6a34
            userCondition: null
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Je kan zelf kiezen waar deze thumbnail staat op de pagina!'
            type: craft\fieldlayoutelements\Tip
            uid: d4870e09-5c50-4264-b515-2a4fd896c9dd
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: thumbnail
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9757016b-74fa-4bc1-a608-750c73587d3e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3a62f4a6-a4f4-4fad-830a-10a5e8dbdc20 # Afbeelding plaatsing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d72c77f3-0dc4-45cd-8d13-ee4a05225717
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: slider
            type: craft\fieldlayoutelements\Heading
            uid: 2f2df4db-be0d-470d-ab0f-35160cd06a5c
            userCondition: null
          -
            elementCondition: null
            fieldUid: d1f9737c-c74a-4ffd-8fde-fed08a33c48c # Afbeelding 2
            instructions: null
            label: 'collectie afbeeldingen'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cfdf4d9-9a62-4060-a585-1cbb5a538315
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 899c793d-0ff3-4611-8076-a9ae2dacf8c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab1e9ae1-eba0-4b77-9d5c-752874dc9fbd # Filter: shop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d8aef9-b0a9-4d18-b80f-5d3205968d8a
            userCondition: null
            warning: null
            width: 100
        name: Filters
        uid: 032ef98a-ce94-406c-ade1-c5b471ab0ed2
        userCondition: null
handle: detail
hasTitleField: true
name: Detail
section: 5e45130b-d008-42a5-9107-35670a0d35c3 # Gallery pagina's
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
