fieldLayouts:
  6fa6f238-dcc3-4b51-a31e-ff1bbebf17cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 76095bcc-3b60-40f1-a9b5-30ae34892a05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9de52d3-491c-45fd-96ca-fa32c8105109
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c60b6aa0-7dc6-442a-9c1b-f19a8052942a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f015654-63be-480a-9494-35a42c3bb3d0
            userCondition: null
            warning: null
            width: 100
        name: Navigatie
        uid: c238a109-8992-47e3-8c5f-df3d9b724596
        userCondition: null
handle: faq
hasTitleField: true
name: FAQ
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
