fieldLayouts:
  9a5a3f88-2d2f-4a94-b539-6958abde5a7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e024900c-3e18-4fa6-9ad0-ef2e8019acdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e6be9b55-51b9-40aa-b515-15630879d7c2 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2feba41-5c04-43a5-b91b-cb30c3078461
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 995c4c91-d868-48bd-be12-16a7b2892d89
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10210e34-0796-4ca6-92ad-bc7d65a34411
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee75781-1976-4f4b-a53e-1b26eba56eda
            userCondition: null
            warning: null
            width: 100
        name: Navigatie
        uid: cc2ca63e-7c17-4fc8-9ea6-fad1f31d19a2
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
