fieldLayouts:
  e88250c1-19c9-4097-9343-900b0ec22813:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3e15224-9b90-4f3b-b8af-7c88a86f6e59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b4babc0-23bb-4518-b042-280303d56249
        userCondition: null
handle: policy
hasTitleField: true
name: Policy
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 7
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
