fieldLayouts:
  306dbed5-0638-42cd-8b74-55f2c25395af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f180cf5b-9061-49c7-84ab-8ac220b729d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 033c064c-dc40-4bd2-9ed0-dfdab37366dd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b85b19f1-eaa4-44ff-b299-4776b80ed451
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcb41e5d-09e8-4a60-a18d-ec294760ea68
            userCondition: null
            warning: null
            width: 100
        name: Navigatie
        uid: 4726764e-ac14-4c53-aba1-7324a556fd75
        userCondition: null
handle: shop
hasTitleField: true
name: Shop
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
