fieldLayouts:
  3da02cfe-023c-4cde-996f-4dd4d4641cfa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c877ed22-e89e-49dd-8307-b1dce949566e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a576e86a-698c-4e39-8bb2-f03c1164f56b # Variant Attribute Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adb8e9f5-4ecf-4fd7-b3a6-492d4420be97
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7a9b0ba-e2da-40c0-8448-71f5f707b846
        userCondition: null
handle: variantAttributeOptionValues
hasTitleField: true
name: 'Variant Attribute Option Values'
section: 44f74a84-4708-412a-a0d4-a4fa2d3f68f5 # Variant Attribute Option Values
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
