columnSuffix: gbbpctiz
contentColumnType: string
fieldGroup: 5abaf161-4cf4-4485-8e4a-2e257439dda4 # Form elements (filters, checkboxes, dropdowns)
handle: displayType
instructions: null
name: 'Display Type'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Dropdown
        -
          - value
          - dropdown
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Radio Buttons'
        -
          - value
          - radioButtons
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: language
type: craft\fields\RadioButtons
