columnSuffix: jgpecxoe
contentColumnType: text
fieldGroup: 94c51b0c-961c-4fd5-904f-5b7871f98cf7 # Text
handle: quote
instructions: null
name: quote
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
