dateModified: 1680621464
email:
  fromEmail: emmavand24@student.arteveldehs.be
  fromName: 'Hannah Van der Haeghen'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: uploads
    type: craft\fs\Local
    url: $UPLOAD_URL
meta:
  __names__:
    0d651d0e-b1d7-45ec-a026-bb77e4ababe3: Navigation # Navigation
    0f24636c-4f10-4522-894b-45739e075b70: 'Email adres' # Email adres
    2a1b88a7-04a1-4876-878f-2253644f6e34: Dummy # Dummy
    2c1c4276-6b14-4857-8873-c475c0a68f0a: 'Pagina''s' # Pagina's
    3c88515a-8032-4a79-94ce-1a74c8074ddf: 'Toon in navigatie' # Toon in navigatie
    3ebf8831-4a21-48bd-a049-493560af4308: Common # Common
    4f3af52d-dc34-45b8-96e8-0355358d1890: About # About
    5f5630f3-da19-4241-a164-79bdca4f52f7: 'LinkedIn link' # LinkedIn link
    7c281d84-4d8d-4b2d-8e36-80a99d919e97: Shop # Shop
    9b464eb3-586e-4db0-bf51-3d00017432b0: English # English
    9db1f9e4-5692-4c0f-ad4a-c18f1475b2a5: Contact # Contact
    19dc3b2d-a870-4e81-91ff-ebdc5f452c29: Images # Images
    56c3e973-0f59-429a-91ed-318814922bbb: FAQ # FAQ
    87a05afd-1262-47cb-acd2-f6aaed1b9640: Websites # Websites
    619a8e46-e785-4b25-90f9-85ba6dcdf9c6: Home # Home
    0657cf24-ecbd-4107-adb2-3a4f69e4ad8b: Policy # Policy
    958e2e03-63a3-4194-b1cf-ebd5fa9fc895: 'Instagram link' # Instagram link
    7521d7d4-bfee-4451-beed-90ad1d724c5b: Work # Work
    072366a1-39d9-4c91-8e57-6eab946ae6fe: Voornaam # Voornaam
    154426f1-715f-4777-9c7f-f599d7641e68: New # New
    361382ab-c268-4ec2-a944-660822aea169: Nederlands # Nederlands
    ae7f6c08-c9a7-4447-9c37-00e0f870e776: 'General Data' # General Data
    b94dc6c9-aae8-45c7-b754-5f6a3c81039a: 'Facebook link' # Facebook link
    c785f0e6-e64a-4275-979b-4b8f8b74ca7a: Achternaam # Achternaam
    dbd11bc6-ad86-4953-959b-f3fb418b6153: 'Toon in footer' # Toon in footer
    e6be9b55-51b9-40aa-b515-15630879d7c2: 'Hero Image' # Hero Image
    f016f34d-e9d9-41bf-86cf-5fc0c29b036c: 'Algemene gegevens' # Algemene gegevens
    fe6b4ecc-45d5-44bf-8dbb-dd6b403e53b7: Telefoonnummer # Telefoonnummer
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: K0K7PE1ZFQX1CKMZ7M723N8A
    schemaVersion: 4.4.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - ''
          -
            - createBrotliFiles
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: false
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - queryStringParam
              - fbclid
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      trackElementQueries: true
      trackElements: true
  commerce:
    edition: lite
    enabled: true
    licenseKey: HCD9OPKMESAZGLLF1DWD0943
    schemaVersion: 4.2.3
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: dist
      publicPath: web
  quick-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 7G0IC4AHSWVI4WSDX11PGUSO
    schemaVersion: 3.0.11
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
