fieldLayouts:
  aa080bb2-eee8-4edd-a3c4-a007eebbec3e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 495525b4-f3f7-495c-b32d-b83652100a4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31bb0e04-2a70-4557-8090-a52c1a2254f2 # Titel 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3519c638-3be3-4a60-8ed4-63573be1cb90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3182e0bd-3780-4fd1-8fc0-a188d3563b84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d # Link 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3c094ab-8ab6-4f84-87fc-33845d3c4b42
            userCondition: null
            warning: null
            width: 100
        name: Contactblok
        uid: 5f6ad3f8-7c08-4750-9e74-408702256b48
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed335616-6cd9-410b-9d9f-5992c89f02c7 # USP
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64b66578-bbbb-4e6b-a276-b3a9af71121a
            userCondition: null
            warning: null
            width: 100
        name: USP
        uid: 98737738-b4c8-4a04-91ca-466528f692c4
        userCondition: null
handle: commonlyUsed
name: 'Veel gebruikte elementen'
sortOrder: 2
