fieldLayouts:
  aa080bb2-eee8-4edd-a3c4-a007eebbec3e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed335616-6cd9-410b-9d9f-5992c89f02c7 # USP
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64b66578-bbbb-4e6b-a276-b3a9af71121a
            userCondition: null
            warning: null
            width: 100
        name: USP
        uid: 98737738-b4c8-4a04-91ca-466528f692c4
        userCondition: null
handle: commonlyUsed
name: 'Veel gebruikte elementen'
sortOrder: 2
