fieldLayouts:
  26d08f1d-9e00-4c06-9b6f-7cd66d3f050d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 072366a1-39d9-4c91-8e57-6eab946ae6fe # Voornaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff012220-04a2-4b23-ab77-352bad37ed7d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c785f0e6-e64a-4275-979b-4b8f8b74ca7a # Achternaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5edad6-e389-4311-b6fa-1eb21691b169
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 922cad9a-c539-431b-81fc-c20243e6e02c
            userCondition: null
          -
            elementCondition: null
            fieldUid: fe6b4ecc-45d5-44bf-8dbb-dd6b403e53b7 # Telefoonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd56650-bf32-428d-9abd-72a37057e8e7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0f24636c-4f10-4522-894b-45739e075b70 # Email adres
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1baac82-4801-41fd-8e85-a086a91eb58b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Social media links'
            type: craft\fieldlayoutelements\Heading
            uid: 904f03db-b82d-425a-a82f-c5a9a69fc3a4
            userCondition: null
          -
            elementCondition: null
            fieldUid: b94dc6c9-aae8-45c7-b754-5f6a3c81039a # Facebook link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22dff426-976a-4867-aedb-5547e92801fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 958e2e03-63a3-4194-b1cf-ebd5fa9fc895 # Instagram link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a9be2a8-351c-4e5d-84ea-812576ffcfdf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f5630f3-da19-4241-a164-79bdca4f52f7 # LinkedIn link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06213468-b251-4a9e-b870-db14bc0ff4dc
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 7f469885-1695-474c-a6b9-edb3f7e07e5c
        userCondition: null
handle: generalData
name: 'Algemene gegevens'
sortOrder: 1
