defaultPlacement: end
enableVersioning: true
handle: contactSubmissions
name: 'Contact berichten'
propagationMethod: all
siteSettings:
  0c227af7-cc71-4e70-a370-a1a6b63ddf75: # Français
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  361382ab-c268-4ec2-a944-660822aea169: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
