defaultPlacement: end
enableVersioning: true
handle: variantAttributeOptionValues
name: 'Variant Attribute Option Values'
propagationMethod: all
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  361382ab-c268-4ec2-a944-660822aea169: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: aa41d2e5-d8e1-4cf5-9dc4-97154a0ceb1f
type: structure
